all:
  hosts:
    node1:
      ansible_host: 135.181.196.89
      ip: 135.181.196.89
      access_ip: 135.181.196.89
    node2:
      ansible_host: 135.181.196.90
      ip: 135.181.196.90
      access_ip: 135.181.196.90
    node3:
      ansible_host: 135.181.196.83
      ip: 135.181.196.83
      access_ip: 135.181.196.83
  children:
    kube-master:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
