= Kubernetes webserver
Author Name <bram.breda@ugent.be>


== prove of concept
=== Manueel
==== [red]#prerequisites#
update all packages:
[source, bash]
----
dnf upgrade
----

==== [red]#installing kubernetes#
[source, bash]
----
cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
exclude=kubelet kubeadm kubectl
EOF

# Set SELinux in permissive mode (effectively disabling it)
sudo setenforce 0
sudo sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

sudo yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes

sudo systemctl enable --now kubelet
----



Disable swapp-off + comment out in fstab file:
[source, bash]
----
swapoff -a

vi /etc/fstab
----

==== [red]#Installing CRI-O#
[source, bash]
----

----




=== ansible
==== [red]#hostfile#
hostfile met 3 werknodes. Er is nog geen HA, hiervoor hebben we minstens 3 masters nodig.

[source, yaml]
----
all:
  children:
    masters:
      hosts:
        master1:
          ansible_host: 135.181.196.89
          ansible_user: root
    workers:
      hosts:
        worker1:
          ansible_host: 135.181.196.90
          ansible_user: root
        worker2:
          ansible_host: 135.181.196.83
          ansible_user: root 
----

==== [red]#VM setup#
Hier worden alle packages upgedate, en wordt swap-off afgelegd.

[source, yaml]
----
----

Swap is een feature dat leidt tot inconstency, dit moet daarom afgezt worden. 

NOTE: Swap space in Linux is used when the amount of physical memory (RAM) is full. If the system needs more memory resources and the RAM is full, inactive pages in memory are moved to the swap space. While swap space can help machines with a small amount of RAM, it should not be considered a replacement for more RAM. Swap space is located on hard drives, which have a slower access time than physical memory.

== kubepsray 
=== [red]#Tasks#
* [x] cri-o
* [x] hostfile
* [ ] test
* [ ] domcument


=== [red]#CRI-O#
change group_vars (inventory/<foldername>/group_vars)

==== all/all.yaml
[source, yaml]
----
download_container: false
skip_downloads: false
etcd_kubeadm_enabled: true
----

==== k8s-cluster/k8s-cluster.yml
[source, yaml]
----
container_manager: crio
----

==== etcd.yml
[source, yaml]
----
etcd_deployment_type: host # optionally and mutually exclusive with etcd_kubeadm_enabled
----

=== [red]#hostfile#
[source, yaml]
----
# ## Configure 'ip' variable to bind kubernetes services on a
# ## different ip than the default iface
# ## We should set etcd_member_name for etcd cluster. The node that is not a etcd member do not need to set the value, or can set the empty string value.
[all]
node1 ansible_host=135.181.196.89   ip=10.0.0.3 etcd_member_name=etcd1
node2 ansible_host=135.181.196.90   ip=10.0.0.2 etcd_member_name=etcd2
node3 ansible_host=135.181.196.83   ip=10.3.0.4 etcd_member_name=etcd3


# ## configure a bastion host if your nodes are not directly reachable
# bastion ansible_host=x.x.x.x ansible_user=some_user

[kube-master]
node1


[etcd]
node1


[kube-node]
node2
node3
[calico-rr]

[k8s-cluster:children]
kube-master
kube-node
calico-rr
----

=== [red]#internal network#
[source, bash]
----
vi /etc/sysconfig/network-scripts/ifcfg-eth1

DEVICE=eth1
BOOTPROTO=dhcp
ONBOOT=yes
----

=== [red]#Test#
[source, bash]
----
# Install dependencies from ``requirements.txt``
sudo pip3 install -r requirements.txt

# Copy ``inventory/sample`` as ``inventory/mycluster``
cp -rfp inventory/sample inventory/mycluster

# Review and change parameters under ``inventory/mycluster/group_vars``
cat inventory/clusterbreda/group_vars/all/all.yml
cat inventory/clusterbreda/group_vars/k8s-cluster/k8s-cluster.yml

# Deploy Kubespray with Ansible Playbook - run the playbook as root
# The option `--become` is required, as for example writing SSL keys in /etc/,
# installing packages and interacting with various systemd daemons.
# Without --become the playbook will fail to run!
ansible-playbook -i inventory/clusterbreda/inventory.ini  --become --become-user=root cluster.yml
----

== Wordpress
=== [red]#MYSQL#
NOTE: MYSQl is een statefull application, hierom is het beter om statefullset te gebruiken. Dit zorgt er ook voor dat PV en PVC anders worden gebruikt. Iedere PVC zal een aparte request zijn dit zou ook beter moeten scalen.

==== mysql-service.yaml
[source, yaml]
----
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
----

==== mysql-statefulset.yaml
[source, yaml]
----
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  serviceName: wordpress-mysql
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: mysql

  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-pv-claim
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-pv-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 20Gi
----

=== [red]#Wordpress#

==== wordpress-service.yaml
[source, yaml]
----
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
----

==== wordpress-pvc.yaml
[source, yaml]
----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
----

==== wordpress-deployment.yaml
[source, yaml]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
----

=== [red]#kustomization.yaml#
[source, yaml]
----
resources:
  - mysql-service.yaml
  - mysql-statefulset.yaml
  - wordpress-service.yaml
  - wordpress-pvc.yaml
  - wordpress-deployment.yaml
----

== Nginx

=== [red]#Working#
NOTE: Nginx uses Serverblocks to run multiple sites form 1 server.

=== [red]#Nginx ingress controller#

[source, bash]
----
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.43.0/deploy/static/provider/baremetal/deploy.yaml
----

